# Generated by Django 2.0.3 on 2018-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, choices=[('m', 'Math'), ('cs', 'Computer Science'), ('g', 'Graphics')], default='m', help_text='An academic topic', max_length=1),
        ),
    ]
